### ISSUE TITLE
Missed Embeddings in the 03-find-similar-articles.sql (line 19) Rest API URL

### ISSUE THREAD

**Issue by MANOMAIDEN** [Azure-Samples/azure-sql-db-openai#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
The following line of code misses the keyword embeddings after <deployment-id>. It is however present in the subsequent functions code etc. Its minor, I just wanted to acknowledge this good stuff and correct the error in the script
Replace
'https://<your-app-name>.openai.azure.com/openai/deployments/<deployment-id>?api-version=2023-03-15-preview'
with
'https://<your-app-name>.openai.azure.com/openai/deployments/<deployment-id>/embeddings?api-version=2023-03-15-preview'

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yorek** [comment]
Thanks, PR #1  fixed this.
